### ISSUE TITLE
Infinite loop on adding Authorize attribute to Home Controller

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-webapp-openidconnect#12]
I added Authorize attribute to Home Controller and made no other changes.
I then deployed it to azurewebsites
I am was able to login fine for few minutes
After that if I try to login to the site InPrivate, I see an infinite loop where the app redirects to login.windows.net, receives an auth code and again redirects to login.windows.net

I am not an admin on the tenant where I created an app. I am a user in the tenant.
My tenant is a federated tenant

**Comment by levalencia** [comment]
I have the exact same problem, any idea?

**Comment by apozgaj** [comment]
I have the same problem as well. I have some fiddler logs that I can send you; just let me know. 

However, in Fiddler one can see requests to login.windows.net. The thing is that at I can see the right identity in OpenId Connect Notifications but during debugging I can see that it never exits from the part of code that handles those notifications. 

Currently I have custom Authorize Attribute that is responding with 403 (like it was suggested on multiple stackoverflow topics) but in that attribute It always enters HandleUnAuthorizedRequest base method and enters openid notifications.

**Comment by dstrockis** [comment]
@apozgaj if you could send over the fiddler trace that would be great - please make sure they have the requests to login.windows.net included, you should be able to see them if you have https decryption turned on.

You shouldn't need a custom authorize attribute - that fix is specific to sites that are doing role-based authorization.  This problem is more likely due to cookie buildup or something like that.  A fiddler trace would help shed more light.

**Comment by apozgaj** [comment]
@dstrockis I've sent you fiddler logs. 

In fact, I must admit that I'm using RBAC app from Azure AD samples. Apologies for posting question here but If you want, I can open it under the "Role Based WebApp with OpenId Connect".

The reason for asking question here is because I have the exact same problem.

In more detailed - the issue is bit hard to reproduce... It happens mostly when you create a new user in AD and that user must change the password on initial login. After chaning the password, that user will end up in infinite loop.

In most most of the cases, restarting the app resolves the problem. Sometimes it requires me to clean the TokenCache table (I'm using Token DB cache). 

Other than this scenario, it occasionally happens fopr regular users - since I have users from other WAAD as well it happens for those users as well.

Also, it happens in same way on Azure and localhost.

**Comment by dstrockis** [comment]
Saw your mail, thanks. I'll have a look as soon as I can.

**Comment by levalencia** [comment]
not sure if this helps, but I was able to make it work with VS 2013, with 2015 is still the same problem.

http://www.luisevalencia.com/2015/06/02/using-azure-aad-graph-office-365-add-in-with-groups-authorization/

https://github.com/OfficeDev/PnP/tree/master/Samples/AzureAD.GroupAuthorization

**Comment by dstrockis** [comment]
Thanks @levalencia.... Your blog there does indeed address an infinite loop issue.  However, I'm not sure the issue here is the same root cause as the one you've solved.  They just both result in an infinite loop... I'll have to check the Fiddler to get a better idea.

**Comment by apozgaj** [comment]
@levalencia i think the code from your blog also refers to this blog: http://www.dushyantgill.com/blog/2014/12/10/roles-based-access-control-in-cloud-applications-using-azure-ad/

and I've implemented that as well... However, I was still getting infinite loop occasionally. The thing I see is that in AuthorizatioCodeReceived I see the right identity from AAD but in my Authorize Attribute it still enters:
if (!ctx.HttpContext.User.Identity.IsAuthenticated)
                base.HandleUnauthorizedRequest(ctx);

this branch.

Thanks for the help

**Comment by apozgaj** [comment]
I hope this will help someone in the future;

It looks like the infinite loop problem went away by implementing two things:
- Kentor CookieSaver
- RequireHttps module

There are plenty of resources for these two things so I will not place any links right now. 

LLaP

**Comment by levalencia** [comment]
How was it implemented? Please ecplain

-----Mensaje original-----
De: "apozgaj" <notifications@github.com>
Enviado el: ‎29/‎06/‎2015 4:24 a. m.
Para: "AzureADSamples/WebApp-OpenIDConnect-DotNet" <WebApp-OpenIDConnect-DotNet@noreply.github.com>
CC: "levalencia" <luise.valencia@gmail.com>
Asunto: Re: [WebApp-OpenIDConnect-DotNet] Infinite loop on adding Authorizeattribute to Home Controller (#12)

I hope this will help someone in the future;
It looks like the infinite loop problem went away by implementing two things:
Kentor CookieSaver 
RequireHttps module 
There are plenty of resources for these two things so I will not place any links right now. 
LLaP

**Comment by apozgaj** [comment]
Install Kentor Cookie Saver via Nuget and add following line:

app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
**app.UseKentorOwinCookieSaver();**
app.UseCookieAuthentication(new CookieAuthenticationOptions() { CookieSecure = CookieSecureOption.Always });

In order to force application to require HTTPS you can:
1) add following in Global.asax:
GlobalFilters.Filters.Add(new RequireHttpsAttribute());

or you can follow some examples on this thread:
http://stackoverflow.com/questions/9823010/how-to-force-https-using-a-web-config-file

**Comment by dstrockis** [comment]
Thanks @apozgaj.  Just for the record, the Kentor Owin Cookie Saver addresses this known issue in the OWIN middleware: https://katanaproject.codeplex.com/workitem/197

**Comment by jwooley** [comment]
We're seeing a similar issue with the redirects. Checking the cookies from chrome, it appears that we are adding a new nonce cookie each time the bounce back occurs. Has anyone else been able to confirm if the kentor fix applies globally, and if so , why does it work.

**Comment by apozgaj** [comment]
I can confirm that implementation of Kentor cookie saver resolved our problem for both multi tenant and single tenant solution. If you prefer you can implement your own cookie manager. 
For more information about Kentor Cookie Saver and how it can help you: https://github.com/KentorIT/owin-cookie-saver

**Comment by thuru** [comment]
I got this error in one of the applications. Used the Kentor middleware and it solved the issue. But I have no clue what this happened suddenly. There was no code changes and the app was running in production for more than 8 months.

**Comment by alenjose007** [comment]
I used [Authorize] attribute. But it is Infinite loop on login page and login url.
We have set the returnUrl as the applications home page https://server ip/name/Home.
Note: We are using MVC4
Could you please advice.

**Comment by apozgaj** [comment]
Consider using Kentor Owin Cookie saver.

**Comment by alenjose007** [comment]
I am using webseal as IDp. Not using Owin authentication. Shall i use Kentor Owin Cookie saver? And could you please help how can it use? please explain.

**Comment by cc-john** [comment]
I struggled with this issue for a while using the OpenIDConnect stuff. After adding some debugging I was seeing validated tokens returned from AAD (OnTokenValidated) and before the home controller was called a 401 unauthorized error came from AAD somehow. Turned out that the template created by VS2015 did not set the **ClientSecret** config value. (ClientSecret = Configuration["Authentication:AzureAd:ClientSecret"]) when building the options object passed to UseOpenIdConnectAuthentication().

Once this was set i was using "oidc" in my Authorize(**ActiveAuthenticationSchemes** = ...) but Startup.cs was using OpenIdConnectDefaults.AuthenticationScheme which resolved to "OpenIdConnect". Matching these up got me rolling.

**Comment by darjiyogen** [comment]
I am also facing same issue in my application. I am using Azure ADFS and RBAC login. It works fine for few users. But If user is member of more than 40+ groups in Azure ADFS it just redirect to infinite loop.

Can anyone have any solution to above issue? Is there is something wrong with ADFS setting?

**Comment by cilmike2** [comment]
@darjiyogen Im having similar issues, but im having it with someone in only 7 groups.  I have noticed that if i don't include the re-direct uri in my options object in startup.auth.cs and i only have one configured in AAD then it works fine.  My problem occurs when  I add an additional URI and then specify which one i want to use in my OpenIdConnectAuthenticationOptions.  Also it seems to work fine locally more often than not, but as soon as i deploy to a standalone IIS server, it does the infinite loop problem.  

From what I can according to the link that @dstrockis posted above the  Kentor Owin Cookie Saver isn't needed on ADAL V3 which is what im using.

**Comment by darjiyogen** [comment]
@cilmike2 Thanks for you suggestion. I've solved issue by splitting Cookie. I noticed that it was issue if Cookie characters are more than browsers limit (> 4096). So to overcome that issue, in set-cookie with around 4000 characters with each and when needed combine all cookie together to get original value.

**Comment by bharney** [comment]
@darjiyogen Thank you for mentioning this issue. We also had a rather large cookie which was greater than the 4096 byte limit. The problem was resolved after addressing the size of the cookie.

**Comment by Shreelekha19** [comment]
My case was little different , hope it helps someone.

I also got the same issue but I knew somewhere it is not redirecting to correct link.
I saw that even though in startup .. redirect property of openid was set to SSL url but when i looked at application properties -->web--> Project url --> it was not pointed to SSL url but http URL.

Pointing to SSL url fixed.
